name: Cypress Tests

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        env:
          BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
          CYPRESS_testUserName: NameFirst
          CYPRESS_testUserLastName: LastNameFirst
          CYPRESS_testUserEmail: ${{ secrets.TEST_USER_EMAIL }}
          CYPRESS_testUserPassWord: ${{ secrets.TEST_USER_PASSWORD }}
        run: npm run test:v1:mochawesome:full
      
      - name: Upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mochawesome-report
          path: mochawesome-report
          retention-days: 7

      - name: Deploy report to gh-pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: mochawesome-report